### ISSUE TITLE
Automatic Email Sender

### ISSUE THREAD

**Issue by abhisheks008** [World-of-ML/Play-With-Python#101]
### Play With Python Repository (Proposing new issue)
:red_circle: **Project Title** : Automatic Email Sender</br>
:red_circle: **Aim** : Create a python app Automatic Email Sender using Python and tkinter.</br>

**********************************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by nik132-eng** [comment]
Full name : Nikunj Champakbhai Rohit
GitHub Profile Link : https://github.com/nik132-eng
Email ID : [19itnik132@ldce.ac.in](mailto:19itnik132@ldce.ac.in)
Participant ID (if applicable):
Approach for this Project : create project using python
What is your participant role? Codepeak contributor

can i take this up?

**Comment by pundarikaksha7** [comment]
Full name : Pundarikaksha
GitHub Profile Link : pundarikaksha7
Email ID : [pundarikakshamohanty@gmail.com]
Approach for this Project :python libraries
What is your participant role? CodePeak

**Comment by abhisheks008** [comment]
@nik132-eng are you willing to take this issue?

**Comment by nik132-eng** [comment]
Yes @abhisheks008

**Comment by abhisheks008** [comment]
Issue assigned to you @nik132-eng
