### ISSUE TITLE
Text Extractor

### ISSUE THREAD

**Issue by abhisheks008** [World-of-ML/Play-With-Python#107]
### Play With Python Repository (Proposing new issue)
:red_circle: **Project Title** : Text Extractor</br>
:red_circle: **Aim** : Create a Text Extractor app which will extract texts from images using Python and also create a GUI for user interaction.</br>

**********************************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by pundarikaksha7** [comment]
Full name : Pundarikaksha
GitHub Profile Link : pundarikaksha7
Email ID : [pundarikakshamohanty@gmail.com](mailto:pundarikakshamohanty@gmail.com)
Approach for this Project :python libraries
What is your participant role? CodePeak

Apologies for the incorrect issue request format

**Comment by vamsikrishnarh7** [comment]
Full name : Durga Vamsi Krishna
GitHub Profile Link : https://github.com/vamsikrishnarh7
Email ID : [vamsikrishnaacpt@gmail.com](mailto:vamsikrishnaacpt@gmail.com)
Participant ID (if applicable):
Approach for this Project : using tkinter and pytesseract modules
What is your participant role? (Mention the Open Source program) CODEPEAK 2022

**Comment by vamsikrishnarh7** [comment]
here is the result of my work : 
https://user-images.githubusercontent.com/89008784/209458964-d2b7259d-e098-4874-ab0d-2989267298ed.mp4

> Full name : Durga Vamsi Krishna GitHub Profile Link : https://github.com/vamsikrishnarh7 Email ID : [vamsikrishnaacpt@gmail.com](mailto:vamsikrishnaacpt@gmail.com) Participant ID (if applicable): Approach for this Project : using tkinter and pytesseract modules What is your participant role? (Mention the Open Source program) CODEPEAK 2022

**Comment by vamsikrishnarh7** [comment]
hey @abhisheks008 if this issue hasn't resolved yet, I would like to work on it.

**Comment by abhisheks008** [comment]
Issue assigned to you @vamsikrishnarh7
