### ISSUE TITLE
Image Grayscalling

### ISSUE THREAD

**Issue by abhisheks008** [World-of-ML/Play-With-Python#108]
### Play With Python Repository (Proposing new issue)
:red_circle: **Project Title** : Image Grayscalling</br>
:red_circle: **Aim** : Create a Image Grayscalling app using Python and also create a GUI for user interaction.</br>

**********************************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by jatin00000** [comment]
Full name : Jatin Kumawat
GitHub Profile Link : https://github.com/jatin00000
Approach for this Project : Using Tkinter for GUI interface and OpenCV for manipulating the image.
What is your participant role? (Mention the Open Source program) CODEPEAK 2022

**Comment by abhisheks008** [comment]
Issue assigned to you @jatin00000
