### ISSUE TITLE
Pong Game

### ISSUE THREAD

**Issue by abhisheks008** [World-of-ML/Play-With-Python#11]
### Play With Python Repository (Proposing new issue)
:red_circle: **Project Title** : Pong Game</br>
:red_circle: **Aim** : Create a Pong Game using Python programming language.</br>

**********************************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by aayushsinha0706** [comment]
Please assign me this issue

Full name : AAYUSH SINHA
GitHub Profile Link : aayushsinha0706
Email ID : aayushsinha0706@outlook.com
Participant ID (if applicable):
Approach for this Project : Will implement this game using pygame module
What is your participant role? (Mention the Open Source program) : CODEPEAK 22

**Comment by Pal8304** [comment]
I would like to work on this issue.
Name :-Palash Jhaveri
Github Profile Link :- https://github.com/Pal8304
Approach for this Project :- Building a pong game using pygame .
CODEPEAK 2022

**Comment by abhisheks008** [comment]
Issue assigned to @aayushsinha0706 on FCFS basis. @Pal8304 you can check out other issues present here.
