### ISSUE TITLE
Weather App

### ISSUE THREAD

**Issue by abhisheks008** [World-of-ML/Play-With-Python#112]
### Play With Python Repository (Proposing new issue)
:red_circle: **Project Title** : Weather App</br>
:red_circle: **Aim** : Create a Weather App using Python and also create a GUI.</br>

**********************************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by pundarikaksha7** [comment]
Kindly assign

**Comment by abhisheks008** [comment]
Comment out with proper credentials @pundarikaksha7

**Comment by pundarikaksha7** [comment]
Full name :Pundarikaksha
GitHub Profile Link :pundarikaksha7
Email ID :pundarikakshamohanty@gmail.com
Participant ID (if applicable):
Approach for this Project :Use weather API
What is your participant role? (Mention the Open Source program)

**Comment by Tushar98644** [comment]
Full name : Tushar Banik
GitHub Profile Link : https://github.com/Tushar98644
Email ID : evilden982@gmail.com
Participant ID (if applicable): 
Approach for this Project : Tkinter module and openweather api
What is your participant role? : codepeak

**Comment by abhisheks008** [comment]
@Tushar98644 issue assigned to you.

**Comment by vamsikrishnarh7** [comment]
Full name : Durga Vamsi Krishna
GitHub Profile Link : https://github.com/vamsikrishnarh7
Email ID : [vamsikrishnaacpt@gmail.com](mailto:vamsikrishnaacpt@gmail.com)
Participant ID (if applicable):
Approach for this Project : using tkinter and openweathermap api
What is your participant role? (Mention the Open Source program) CODEPEAK 2022

**Comment by vamsikrishnarh7** [comment]
hey @abhisheks008 if this issue hasn't resolved yet, I would like to work on it.
here is the result of my work :

https://user-images.githubusercontent.com/89008784/210133595-aac251a5-b262-4bae-a728-283158896152.mp4

I will be grateful to you if u assign this to me :)

**Comment by abhisheks008** [comment]
@Tushar98644 any updates on this issue? As this is being assigned 2 weeks back, it should be completed till date.

**Comment by abhisheks008** [comment]
Issue unassigned from @Tushar98644 due to inactivity.

**Comment by vamsikrishnarh7** [comment]
@abhisheks008 can you please assign this to me
