### ISSUE TITLE
Quiz Game

### ISSUE THREAD

**Issue by abhisheks008** [World-of-ML/Play-With-Python#15]
### Play With Python Repository (Proposing new issue)
:red_circle: **Project Title** : Quiz Game</br>
:red_circle: **Aim** : Create a Quiz Game using Python Programming language.</br>

**********************************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by joleyasarthak** [comment]
Hey I would like to contribute to this issue.
Full name : Sarthak Joleya
GitHub Profile Link : github.com/joleyasarthak
Email ID : [sarthakjoleya@gmail.com](mailto:sarthakjoleya@gmail.com)
Participant ID (if applicable):
Approach for this Project : I will make a Quiz game using API to fetch questions and make GUI using Tkinter Library
What is your participant role? (Mention the Open Source program) CodePeaks 2022

**Comment by abhisheks008** [comment]
Issue assigned to you @joleyasarthak
