### ISSUE TITLE
Bug: The age calculator does not work as expected

### ISSUE THREAD

**Issue by SSHSRN** [World-of-ML/Play-With-Python#153]
I was just checking the age calculator project when I noticed that the code works for correct inputs, but the error handling is not done properly as shown in the below screenshot.

![image](https://user-images.githubusercontent.com/62781914/210404733-a2b98720-e17f-4993-ac97-84b9a9ff3016.png)

Kindly assign me this issue under CodePeak-2022 so that I can work on the same.

**Comment by abhisheks008** [comment]
Great finding. Complete your previous PR and this is assigned to you.
@SSHSRN
