### ISSUE TITLE
[Enhancement] Haunted House Game - Add GUI

### ISSUE THREAD

**Issue by abhisheks008** [World-of-ML/Play-With-Python#159]
### Play With Python Repository (Proposing new issue)
:red_circle: **Project Title** : Haunted House Game</br>
:red_circle: **Aim** : Haunted House game is present here in this repository. The game has no GUI, it is being played in the terminal. Need to create a GUI, which will make the game more interactive.</br>

**********************************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by bcsamrudh** [comment]
@abhisheks008 .I could not understand the issue. How should the GUI be, should it contain graphics or a simple text-based one is enough?

**Comment by abhisheks008** [comment]
The existing Haunted House game does not have any GUI as it was in a command line format. You need to make a GUI for that game.

**Comment by bcsamrudh** [comment]
Full name : B C SAMRUDH
GitHub Profile Link: https://github.com/bcsamrudh
Email ID: samrudhbc@gmail.com
Participant ID (if applicable):
Approach for this Project: Creating a GUI for the existing Haunted House Game
What is your participant role? (Mention the Open Source program) DWOC23

**Comment by abhisheks008** [comment]
Issue assigned to you @bcsamrudh
