### ISSUE TITLE
Hangman Game

### ISSUE THREAD

**Issue by abhisheks008** [World-of-ML/Play-With-Python#16]
### Play With Python Repository (Proposing new issue)
:red_circle: **Project Title** : Hangman Game</br>
:red_circle: **Aim** : Create a Hangman Game using Python programming language.</br>

**********************************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by aayushsinha0706** [comment]
Hello Abhishek,
I would like to work on this project

**Full Name : ** Aayush Sinha
**Github profile Link :** https://github.com/aayushsinha0706
**Email Id: ** aayushsinha0706@outlook.com
**Approach for this project: ** I will be using random module and txt file containing all words required for the game. I will implement  a function, called hangman, that will start up and carry out an interactive Hangman game between a player and the computer. 
** What is your participant role? : ** CODEPEAK22

**Comment by abhisheks008** [comment]
Thanks @aayushsinha0706 for showing interest. Contributions will be counted on or after December 5, 2022 as per the timeline given by the Codepeak team. See you soon!

**Comment by aayushsinha0706** [comment]
Should I create another pull request.

**Comment by NihalAhmadKhan** [comment]
I would like to contribute in this project

**Comment by abhisheks008** [comment]
Do not take it otherwise @aayushsinha0706, as you are in an open source event you need to follow the rules. I understand you have commented here a day back, and now you have contributed here with your PR. The problem is I proceed your PR others will notice that and they will create their PRs without commenting and getting assigned the issue. I hope you understand.

Anyways this issue is assigned to you. No need to create a fresh PR, I'll evaluate that.

**Comment by aayushsinha0706** [comment]
Perfectly understandable ! I apologise for misunderstanding caused 😄
