### ISSUE TITLE
Binary Calculator App [with GUI]

### ISSUE THREAD

**Issue by abhisheks008** [World-of-ML/Play-With-Python#163]
### Play With Python Repository (Proposing new issue)
:red_circle: **Project Title** : Binary Calculator App</br>
:red_circle: **Aim** : Create a Binary calculator app.</br>

**********************************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by keyvanmj** [comment]
*   Full name: Keyvan Majidi
*   GitHub Profile Link : https://github.com/keyvanmj
*   Email ID : [keyvanmj5@gmail.com](mailto:keyvanmj5@gmail.com)
*   Participant ID (if applicable): Not sure how to find it
*    Approach for this Project:
     *   binary calculator app using builtin python modules and tkinter for the GUI.
*    What is your participant role? (Mention the Open Source program) Delta WoC 2023

**Comment by abhisheks008** [comment]
Assigned @keyvanmj
