### ISSUE TITLE
Cartooning Image [with GUI]

### ISSUE THREAD

**Issue by abhisheks008** [World-of-ML/Play-With-Python#169]
### Play With Python Repository (Proposing new issue)
:red_circle: **Project Title** : Cartooning Image</br>
:red_circle: **Aim** : Create an app which will cartoonify the images.</br>

**********************************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by bcsamrudh** [comment]
Full name :B C SAMRUDH
GitHub Profile Link:https://github.com/bcsamrudh
Email ID: samrudhbc@gmail.com
Participant ID (if applicable): bcsamrudh
Approach for this Project: Make a program that cartoonifies the image.
What is your participant role? (Mention the Open Source program) DWOC 2023

**Comment by abhisheks008** [comment]
Issue assigned to you @bcsamrudh
