### ISSUE TITLE
News App [with GUI]

### ISSUE THREAD

**Issue by bcsamrudh** [World-of-ML/Play-With-Python#179]
### Play With Python Repository (Proposing new issue)
:red_circle: **News App** : </br>
:red_circle: **To Create an app that gives you today's news** : </br>

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue:**
- Full name: BC SAMRUDH
- GitHub Profile Link: https://github.com/bcsamrudh
- Email ID: samrudhbc@gmail.com
- Approach for this Project: I have used Beautiful Soup and Requests to scrape the data from a News website.
- The GUI has been made using tkinter
- Open Source Program: Delta Force Winter of Code
*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open-source journey ahead. 😎

**Comment by abhisheks008** [comment]
@bcsamrudh have you guys joined any discord channel for communication? I have not joined any such communication channel as a result I can't communicate with other people participating here in this program. It's getting difficult for me. Can you share me the discord channel link in my email, abhishek.opensource@gmail.com
