### ISSUE TITLE
Text-Utility [GUI needed]

### ISSUE THREAD

**Issue by yash240408** [World-of-ML/Play-With-Python#184]
### Play With Python Repository (Proposing new issue)
:red_circle: **Project Title** : Text Utility</br>
:red_circle: **Aim** : Text Analysis</br>

**********************************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Yash Mistry
- GitHub Profile Link : https://github.com/yash240408
- Email ID : yash.mistry.g43@gmail.com
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
In which open source program are you participating? Please mention that.
@yash240408

**Comment by abhisheks008** [comment]
@yash240408 work on this issue once your exams are over.

**Comment by yash240408** [comment]
> @yash240408 work on this issue once your exams are over.

Definitely sir, waiting for my exams to get over.
