### ISSUE TITLE
Bookmarks Organizer

### ISSUE THREAD

**Issue by vaibhavx42** [World-of-ML/Play-With-Python#187]
### Play With Python Repository (Proposing new issue)
:red_circle: **Project Title** : Bookmarks Exporter</br> 
:red_circle: **Aim** : The goal of this project is to provide an easy-to-use command-line tool that extracts and organizes bookmarks from the Chrome bookmarks file and saves them in a user-specified format(HTML/PDF/TXT).</br> 

**********************************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Vaibhav Bhardwaj
- GitHub Profile Link : https://github.com/vaibhavx42
- Email ID : bhardwajvaibhav186@gmail.com
- Participant ID (if applicable):
- Approach for this Project : Python Program for Exporting and Organizing bookmarks.
- What is your participant role? DWOC^23

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
Command line tools are not required. if you can come up with an user interface then you can good to go.

**Comment by vaibhavx42** [comment]
> Command line tools are not required. if you can come up with an user interface then you can good to go.

Yes I've added gui . Can I submit a PR for same?

**Comment by vaibhavx42** [comment]
Please assign the DWOC Label @abhisheks008
