### ISSUE TITLE
Tiles Puzzle Game

### ISSUE THREAD

**Issue by abhisheks008** [World-of-ML/Play-With-Python#27]
### Play With Python Repository (Proposing new issue)
:red_circle: **Project Title** : Tiles Puzzle Game</br>
:red_circle: **Aim** : Implement the Tiles Puzzle Game using Python.</br>

**********************************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by mauryakshitij** [comment]
I would like to work on this issue

Full name : Kshitij Maurya
GitHub Profile Link : https://github.com/mauryakshitij
Email ID : kkmaurya2004@gmail.com
Participant ID (if applicable): mauryakshitij
Approach for this Project : Pygame
What is your participant role? (Mention the Open Source program) Codepeak

**Comment by abhisheks008** [comment]
Issue assigned to you @mauryakshitij
