### ISSUE TITLE
The Haunted House Game

### ISSUE THREAD

**Issue by abhisheks008** [World-of-ML/Play-With-Python#31]
### Play With Python Repository (Proposing new issue)
:red_circle: **Project Title** : The Haunted House Game</br>
:red_circle: **Aim** : Implement the Haunted House Game using Python.</br>

**********************************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by aishvi-g** [comment]
are we expected to follow the map approach here ? or can we use riddles for passing the levels?

**Comment by abhisheks008** [comment]
You can use any of them you are comfortable with @aishvi-g.

**Comment by G0V1NDK** [comment]
Can I work on this? @abhisheks008

**Comment by abhisheks008** [comment]
Issue assigned to you @G0V1NDK
