### ISSUE TITLE
Dice with Death Game

### ISSUE THREAD

**Issue by abhisheks008** [World-of-ML/Play-With-Python#34]
### Play With Python Repository (Proposing new issue)
:red_circle: **Project Title** : Dice with Death Game</br>
:red_circle: **Aim** : Implement the Dice with Death Game using Python.</br>

**********************************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by devika-singh** [comment]
Full name : Devika Singh
GitHub Profile Link :https://github.com/devika-singh
Email ID :devikas.iitg@gmail.com
Participant ID (if applicable):devika-singh
Approach for this Project : make a python game with 2d graphics
What is your participant role? CODEPEAK 2022

**Comment by devika-singh** [comment]
@abhisheks008 Please assign me this issue

**Comment by abhisheks008** [comment]
Issue assigned to you @devika-singh
