### ISSUE TITLE
Tic Tac Toe Game

### ISSUE THREAD

**Issue by abhisheks008** [World-of-ML/Play-With-Python#4]
### Play With Python Repository (Proposing new issue)
:red_circle: **Project Title** : Tic Tac Toe Game</br>
:red_circle: **Aim** : Create a Tic Tac Toe Game using Python Programming language.</br>

**********************************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
@tripti033 if you wanna work on this issue of **Tic Tac Toe** game, you can comment out here to get the issue assigned to you. After that, you can start making the PR for this problem statement.

**Comment by SanyaGupta19** [comment]
I wanna work on this issue

**Comment by abhisheks008** [comment]
@SanyaGupta19 you can work on one issue at a time. In which issue you wanna work on first?

**Comment by SanyaGupta19** [comment]
@abhisheks008 I would like to work on this first

**Comment by abhisheks008** [comment]
Issue assigned to you @SanyaGupta19. Go ahead🎉

**Comment by joleyasarthak** [comment]
Hey, I would like to contribute to this issue. 
Full name : Sarthak Joleya
GitHub Profile Link : https://github.com/joleyasarthak
Email ID : sarthakjoleya@gmail.com
Participant ID (if applicable): (dont have it yet)
Approach for this Project : I will try to replicate google tic tac toe theme and create it in python using pygame. 
What is your participant role? CodePeaks 2022

**Comment by abhisheks008** [comment]
Nice approach! Issue assigned to you @joleyasarthak. Go ahead!
