### ISSUE TITLE
Hacking Mini Game

### ISSUE THREAD

**Issue by abhisheks008** [World-of-ML/Play-With-Python#42]
### Play With Python Repository (Proposing new issue)
:red_circle: **Project Title** : Hacking Mini Game</br>
:red_circle: **Aim** :  Create and implement the Hacking Mini Game using Python.</br>

**********************************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Tushar98644** [comment]
assign it to me ....

**Comment by abhisheks008** [comment]
Please follow the issue template and comment out accordingly @Tushar98644

**Comment by SSHSRN** [comment]
Hey @abhisheks008!

I would like to work on this issue!

* Full name: Srihari S
* GitHub profile link: https://github.com/SSHSRN
* Email ID: sshsrn@gmail.com
* Participant ID (if applicable): Not sure how to find it
* Approach for this Project:
    * Just googled and found out that in this game, the player must hack a computer by guessing a seven-letter word used as the secret password. The computer’s memory banks display the possible words, and the player is given hints as to how close each guess was. For example, if the secret password is MONITOR but the player guessed CONTAIN, they are given the hint that two out of seven letters were correct, because both MONITOR and CONTAIN have the letter O and N as their second and third letter.
    * Seeing the description, I believe it is easy to implement in python and that I can do it.
* What is your participant role? (Mention the Open-Source program): CodePeak 2022

Kindly assign me this issue so that I can work on the same, and I would need some time for submitting the PR as we have our end-sem exams going now, which ends on 13th December.

**Comment by abhisheks008** [comment]
First time I have got such a detailed approach while taking an issue! Really appreciated. No issues about the timeline, just make sure you are able to solve the issue within the program deadline otherwise your contributions will not be counted as a part of Codepeak 2022 event.

Issue assigned to you @SSHSRN
