### ISSUE TITLE
Screen Recorder App

### ISSUE THREAD

**Issue by abhisheks008** [World-of-ML/Play-With-Python#78]
### Play With Python Repository (Proposing new issue)
:red_circle: **Project Title** : Screen Recorder App</br>
:red_circle: **Aim** : Create a Screen Recorder App using Python.</br>

**********************************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by nik132-eng** [comment]
Full name : Nikunj Champakbhai Rohit
GitHub Profile Link: https://github.com/nik132-eng
Email ID : [19itnik132@ldce.ac.in](mailto:19itnik132@ldce.ac.in)
Participant ID (if applicable):
Approach for this Project: create project using python
What is your participant role? Codepeak contributor

**Comment by abhisheks008** [comment]
One issue at a time.

**Comment by nik132-eng** [comment]
Can you assign me now?

**Comment by abhisheks008** [comment]
Issue assigned to you @nik132-eng

**Comment by abhisheks008** [comment]
Updates please @nik132-eng

**Comment by nik132-eng** [comment]
There was some error while compiling time. Sorting out that and update you soon

**Comment by abhisheks008** [comment]
Cool! Finish it within the deadline, this is not gonna count.
