### ISSUE TITLE
Music Player App

### ISSUE THREAD

**Issue by abhisheks008** [World-of-ML/Play-With-Python#80]
### Play With Python Repository (Proposing new issue)
:red_circle: **Project Title** : Music Player App</br>
:red_circle: **Aim** : Create a Music Player App using Python.</br>

**********************************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by joleyasarthak** [comment]
Do we get more points for working on hard labelled problem?? @abhisheks008

**Comment by abhisheks008** [comment]
Hard issues will carry 20 points and depending on the work done by you, bonus points are there to encourage your contribution.
@joleyasarthak

**Comment by aayushsinha0706** [comment]
Please assign me this issue

Full name : AAYUSH SINHA
GitHub Profile Link : aayushsinha0706
Email ID : aayushsinha0706@outlook.com
Participant ID (if applicable): 
Approach for this Project : I will be using number of libraries such as tinter , os , pyagme to create this
What is your participant role? (Mention the Open Source program) : CODEPEAK 22

**Comment by abhisheks008** [comment]
Issue assigned to you @aayushsinha0706
