### ISSUE TITLE
Random Password Generator

### ISSUE THREAD

**Issue by abhisheks008** [World-of-ML/Play-With-Python#81]
### Play With Python Repository (Proposing new issue)
:red_circle: **Project Title** : Random Password Generator</br>
:red_circle: **Aim** : Create a Random Password Generator app using Python.</br>

**********************************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by joleyasarthak** [comment]
Hey @SSHSRN, you may start working on this issue, and create a PR, as @abhisheks008 is inactive till 16th Dec. Please refer [this](https://github.com/World-of-ML/Play-With-Python/blob/main/CONTRIBUTING.md), for how to contribute. Hope it helps.

**Comment by abhisheks008** [comment]
Issue assigned to you @SSHSRN.
Implement a GUI while making this project.
