### ISSUE TITLE
WiFi Password Saver App

### ISSUE THREAD

**Issue by abhisheks008** [World-of-ML/Play-With-Python#82]
### Play With Python Repository (Proposing new issue)
:red_circle: **Project Title** : WiFi Password Saver App</br>
:red_circle: **Aim** : Create a WiFi Password Saver App using Python.</br>

**********************************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by SSHSRN** [comment]
Hey @abhisheks008!

I would like to work on this issue!

* Full name: Srihari S
* GitHub profile link: https://github.com/SSHSRN
* Email ID: sshsrn@gmail.com
* Participant ID (if applicable): Not sure how to find it
* Approach for this Project:
    * Just googled and found out that there are libraries and modules for saving the wifi passwords of the networks of the device.
* What is your participant role? (Mention the Open-Source program): CodePeak 2022

Kindly assign me this issue so that I can work on the same!

**Comment by abhisheks008** [comment]
Issue assigned to you @SSHSRN

**Comment by SSHSRN** [comment]
As I am getting many errors while trying the code for this issue, kindly unassign me this issue.

**Comment by keyvanmj** [comment]
* Full name: Keyvan Majidi
* GitHub Profile Link : https://github.com/keyvanmj
* Email ID : keyvanmj5@gmail.com
* Participant ID (if applicable): Not sure how to find it
* Approach for this Project: 
   * It can be done using subprocess module for wi-fi password and for GUI im using tkinter
* What is your participant role? (Mention the Open Source program) Delta WoC 2023

**Comment by abhisheks008** [comment]
Assigned @keyvanmj
