### ISSUE TITLE
Morse Code Converter

### ISSUE THREAD

**Issue by abhisheks008** [World-of-ML/Play-With-Python#85]
### Play With Python Repository (Proposing new issue)
:red_circle: **Project Title** : Morse Code Converter</br>
:red_circle: **Aim** : Create a Morse Code Converter using Python.</br>

**********************************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by aayushsinha0706** [comment]
please assign me this issue

**Comment by abhisheks008** [comment]
Can you elaborate the approach you wanna take?
@aayushsinha0706

**Comment by aayushsinha0706** [comment]
Full name : Aayush Sinha
GitHub Profile Link : aayushsinha0706
Email ID : aayushsinha0706@outlook.com
Participant ID (if applicable): 
Approach for this Project : I will be using dictionary data structure or implementing a cipher such as a morse code
What is your participant role? (Mention the Open Source program) : CODEPEAK 22

**Comment by abhisheks008** [comment]
Use tkinter library for creating a GUI and make it user interactive rather than command line oriented.
Issue assigned to you @aayushsinha0706
