### ISSUE TITLE
Age Calculator

### ISSUE THREAD

**Issue by abhisheks008** [World-of-ML/Play-With-Python#91]
### Play With Python Repository (Proposing new issue)
:red_circle: **Project Title** : Age Calculator</br>
:red_circle: **Aim** : Create an Age Calculator app using Python.</br>

**********************************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Abhay04ch** [comment]
Name: Abhay Chauhan
GitHub Profile Link: https://github.com/Abhay04ch
Email ID: chauhan04abhay@gmail.com
Approach: Create an age calculator app using inbuilt python modules.
Participant Role: `CODEPEAK 2022`

**Comment by abhisheks008** [comment]
Issue assigned to you @Abhay04ch
