### ISSUE TITLE
Alarm Clock

### ISSUE THREAD

**Issue by abhisheks008** [World-of-ML/Play-With-Python#92]
### Play With Python Repository (Proposing new issue)
:red_circle: **Project Title** : Alarm Clock</br>
:red_circle: **Aim** : Create an Alarm Clock using Python</br>

**********************************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by G0V1NDK** [comment]
Full name : Govind Kushwaha
GitHub Profile Link : https://github.com/G0V1NDK
Email ID : [govind.kush2001@gmail.com](mailto:govind.kush2001@gmail.com)
Participant ID (if applicable):
Approach for this Project : Using datetime and playsound module
What is your participant role? Codepeak'22
