### ISSUE TITLE
Stopwatch

### ISSUE THREAD

**Issue by abhisheks008** [World-of-ML/Play-With-Python#93]
### Play With Python Repository (Proposing new issue)
:red_circle: **Project Title** : Stopwatch</br>
:red_circle: **Aim** : Create a Stopwatch using Python.</br>

**********************************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by devika-singh** [comment]
Full name :Devika Singh
GitHub Profile Link :https://github.com/devika-singh
Email ID :[devikas.iitg@gmail.com](mailto:devikas.iitg@gmail.com)
Participant ID (if applicable): devika-singh
Approach for this Project : Make a console application that works like a stopwatch
What is your participant role? (Mention the Open Source program) CODEPEAK 2022

**Comment by vamsikrishnarh7** [comment]
Full name : Durga Vamsi Krishna
GitHub Profile Link : https://github.com/vamsikrishnarh7
Email ID : [vamsikrishnaacpt@gmail.com](mailto:vamsikrishnaacpt@gmail.com)
Participant ID (if applicable):
Approach for this Project : using tkinter library and datetime modules
What is your participant role? (Mention the Open Source program) CODEPEAK 2022

**Comment by vamsikrishnarh7** [comment]
> Full name : Durga Vamsi Krishna GitHub Profile Link : https://github.com/vamsikrishnarh7 Email ID : [vamsikrishnaacpt@gmail.com](mailto:vamsikrishnaacpt@gmail.com) Participant ID (if applicable): Approach for this Project : using tkinter library and datetime modules What is your participant role? (Mention the Open Source program) CODEPEAK 2022

here is the result of my work :


https://user-images.githubusercontent.com/89008784/209674315-91df1f30-8c2e-4822-8e4d-5fc5e352316a.mp4

**Comment by vamsikrishnarh7** [comment]
hey @abhisheks008 abhisheks008 if this issue hasn't resolved yet, I would like to work on it.

**Comment by abhisheks008** [comment]
Issue assigned to you @vamsikrishnarh7
