### ISSUE TITLE
QR Code Generator

### ISSUE THREAD

**Issue by abhisheks008** [World-of-ML/Play-With-Python#96]
### Play With Python Repository (Proposing new issue)
:red_circle: **Project Title** : QR Code Generator</br>
:red_circle: **Aim** : Create a QR Code Generator app using Python.</br>

**********************************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by nik132-eng** [comment]
Please assign me this issue.

Full name : Nikunj Champakbhai Rohit
GitHub Profile Link : https://github.com/nik132-eng
Email ID : [19itnik132@ldce.ac.in](mailto:19itnik132@ldce.ac.in)
Participant ID (if applicable):
Approach for this Project : create project using python
What is your participant role? Codepeak contributor

**Comment by nik132-eng** [comment]
Please assign me this issue.

Full name : Nikunj Champakbhai Rohit
GitHub Profile Link : https://github.com/nik132-eng
Email ID : [19itnik132@ldce.ac.in](mailto:19itnik132@ldce.ac.in)
Participant ID (if applicable):
Approach for this Project : create project using python
What is your participant role? Codepeak contributor

**Comment by nik132-eng** [comment]
can you assign me now?

**Comment by abhisheks008** [comment]
First complete your previous issue, then only you can work on the new one. As the guidelines suggests one issue at a time.

**Comment by joleyasarthak** [comment]
Hey I would like to contribute to this issue. 
Full name : Sarthak Joleya
GitHub Profile Link : github.com/joleyasarthak
Email ID : sarthakjoleya@gmail.com
Participant ID (if applicable): 
Approach for this Project : I will make a QR code generator using tkinter library 
What is your participant role? (Mention the Open Source program) CodePeaks 2022

**Comment by abhisheks008** [comment]
@joleyasarthak try to find out different issues as @nik132-eng is showing real interest for this issue for several times. Hope you understand.

**Comment by joleyasarthak** [comment]
> @joleyasarthak try to find out different issues as @nik132-eng is showing real interest for this issue for several times. Hope you understand.

Sure No Problem Sir.

**Comment by nik132-eng** [comment]
can i work on this now? as I finished previous PR

**Comment by abhisheks008** [comment]
Issue assigned to you @nik132-eng. Make sure you are creating an app, and it'll have an user interactive GUI.
