### ISSUE TITLE
Audio Book

### ISSUE THREAD

**Issue by abhisheks008** [World-of-ML/Play-With-Python#99]
### Play With Python Repository (Proposing new issue)
:red_circle: **Project Title** : Audio Book</br>
:red_circle: **Aim** : Create an Audio Book using Python and tkinter.</br>

**********************************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by mathew4STAR** [comment]
Full name : Mathew Hans
GitHub Profile Link : https://github.com/mathew4STAR
Email ID : mathewph249@gmail.com
Participant ID (if applicable): 
Approach for this Project : Using pyttsx3 for speed to text, PyPDF2 to extract text from pdfs, and tkinter for UI
What is your participant role?: CODEPEAK2022

**Comment by abhisheks008** [comment]
Issue assigned to you @mathew4STAR
